services:
  fast-api:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    image: fastapi
    container_name: fastapi
    ports:
      - "8000:8000"
    networks:
      - backend

  prometheus:
      image: prom/prometheus:latest
      container_name: prometheus
      ports:
        - "9090:9090"
      environment:
        - FASTAPI_PORT=8000
      volumes:
        - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      command:
        - "--config.file=/etc/prometheus/prometheus.yml"
      depends_on:
        - fast-api
        - cadvisor
      networks:
        - backend 

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
    - 8080:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
    - fast-api
    networks:
      - backend 

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - ./docker/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./docker/grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/FastAPIMetricsDashboars.yml
      - ./docker/grafana/FastAPI_MetricsDashboard.json:/etc/grafana/provisioning/dashboards/FastAPI_MetricsDashboard.json
    networks:
      - backend

networks:
  backend:
    name: backend
    driver: bridge
