[tool.poetry]
name = "oi-ai-mleng-takehome"
version = "0.1.0"
description = ""
authors = ["Bruno Aguiar <bruno.f.o.aguiar@gmail.com>"]
readme = "README.md"
packages = [{include = "oi"}]

[tool.poetry.dependencies]
python = "^3.8"
torch = "^2.3.1"
torchvision = "^0.18.1"
black = "^24.4.2"
isort = "^5.13.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
