{
 "title": "FastAPI Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "FastAPI's HTTP Request Durations in Seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum{job=\"fastapi_app\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FastAPI's HTTP Requests Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_requests_total{job=\"fastapi_app\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FastAPI's Memory Usage",
   "type": "timeseries",
   "description": "FastAPI's Memory Usage in MB",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=\"fastapi\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FastAPI's CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "container_cpu_usage_seconds_total{name=\"fastapi\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}