global:
  scrape_interval: 15s
  scrape_timeout: 10s

scrape_configs:

  - job_name: prometheus
    honor_timestamps: true
    metrics_path: /metrics
    scheme: http
    follow_redirects: true
    static_configs:
    - targets:
      - localhost:9090

  - job_name: 'fastapi_app'
    metrics_path: /metrics
    static_configs:
      - targets: ['fastapi:8000']

  - job_name: 'cadvisor'
    static_configs:
    - targets:
      - cadvisor:8080
