name: Run CI tests
run-name: ${{ github.actor }}'s code is being tested 🚀
on: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:latest
        options: --privileged
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry 

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ' 3.10.14'
          cache: 'poetry'
          cache-dependency-path: poetry.lock

      - name: Setup python environment
        run: poetry env use 3.10.14

      - name: Install project dependencies
        run: poetry install  --no-interaction --no-root

      - name: Run tests
        run: poetry run inv tests

